### ISSUE TITLE
Are the Releases on GitHub official production releases?

### ISSUE THREAD

**Issue by apjanke** [rdiankov/collada-dom#19]
The [releases page](https://github.com/rdiankov/collada-dom/releases) for this project shows releases for 2.4.2, 2.4.3, and 2.4.4. But these versions aren't present on the SourceForge page. Are these official releases of the project suitable for production use?

And is this project here on GitHub a fork of the [original SourceForge project](http://sourceforge.net/projects/collada-dom/), or is this where new development on the same project is happening? I'm not sure what "very lightweight version" (in the README) means.

**Comment by rdiankov** [comment]
excellent questions. we use collada-dom heavily in openrave  and since no one was maintaining it, we decided to fork it and continue on with bug fixes and general development.
very light weight means we only use the dom/src dom/include directories which only compiles the xml collada parser library.
as far as i'm aware, this project is the only updated collada-dom repo.
